# Insira aqui o comando FROM 
FROM 

# Aqui vem o comando para instalar a biblioteca extra
RUN 

# Insira aqui os comandos COPY tanto para o arquivo main.py quanto para o arquivo connector
COPY 
COPY 

# Insira aqui o comando CMD
CMD ["python", "main.py"]